freq_walk: 0.5

Duty: 0.7
phShifts:
- 0.35
- 0.5
- 0.4
- 0.9
ellipse_a: 0.1
ellipse_b: 0.05

midstance:
  row: 3
  col: 4
  data: [0,     0.0,    0.,     0.,
        0.1984, -0.23,  0.23,   -0.23,
        -0.132, -0.132, -0.132, -0.132]
  # - [0.0, 0.0, 0.0, 0.0]
  # - [0.1984, -0.23, 0.23, -0.23]
  # - [-0.132, -0.132, -0.132, -0.132]

swing_height:
- 0.05
- 0.07
- 0.07
- 0.07
swing_width:
- 0.03
- 0.03
- 0.03
- 0.03

spineCPGscaling: 0.15

qNULL:
  dt: d
  data: [0,0,0,0,
         0,0,0,0,
         0,0,0,0,
         0,0,0,0]
# - [0,0,0,0]
# - [0,0,0,0]
# - [0,0,0,0]
# - [0,0,0,0]




# l_trunk:
# - 0.08
# - 0.155
# - 0.155
# - 0.075

# IG: 0.465

# length_FL:
# - [0, 0.051, 0]
# - [0, 0, 0]
# - [0, 0.1474, 0]
# - [0, 0, 0]
# - [0, 0, -0.132]

# length_FR:
# - [0, -0.051, 0]
# - [0, 0, 0]
# - [0, -0.1474, 0]
# - [0, 0, 0]
# - [0, 0, -0.132]

# length_HL: 
# - [0, 0.051, 0]
# - [0, 0, 0]
# - [0, 0.1474, 0]
# - [0, 0, 0]
# - [0, 0, -0.132]

# length_HR: 
# - [0, -0.051, 0]
# - [0, 0, 0]
# - [0, -0.1474, 0]
# - [0, 0, 0]
# - [0, 0, -0.132]

# l0: 0.051
# l1: 0
# l2: 0.1474
# l3: 0
# l4: 0.132

# constrS: 30.0

# ikin_lam:
# - 0.01
# - 0.01

# ikin_M:
# - [0.01,	0,	0,	0]
# - [0,	0.01,	0,	0]
# - [0,	0,	0.01,	0]
# - [0,	0,	0,	0.01]

# ikin_max_dist: 0.03
# ikin_tol: 0.001
# ikin_maxIter: 4
# ikin_constr_penalty: 
# - 0.001 
# - 2
# - 1.01

# constrFL:
# - [-50., -75., -50., -20.]
# - [50.,  75.,	50., 75.]

# constrHL:
# - [-50., -75., -50., -20.]
# - [50.,  75.,	50., 75.]

